"""Create new indexes

Revision ID: 0af84b1e6088
Revises: 58ea61a79a40
Create Date: 2018-06-22 13:21:46.996138

"""
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0af84b1e6088'
down_revision = '58ea61a79a40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_request_tesla_id', 'request', [sa.text('tesla_id ASC')], unique=False)
    op.create_index('idx_request_result_request_id', 'request_result', [sa.text('request_id ASC')], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_request_result_request_id', table_name='request_result')
    op.drop_index('idx_request_tesla_id', table_name='request')
    # ### end Alembic commands ###
