"""Add Intrument Thresholds

Revision ID: c7a09ba2a9ca
Revises: 060be25bdca8
Create Date: 2018-04-11 11:17:41.022547

"""
#  TeSLA Admin
#  Copyright (C) 2019 Universitat Oberta de Catalunya
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c7a09ba2a9ca'
down_revision = '060be25bdca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_thresholds',
        sa.Column('created', sa.DateTime(), nullable=False),
        sa.Column('updated', sa.DateTime(), nullable=True),
        sa.Column('instrument_id', sa.BigInteger(), nullable=False),
        sa.Column('low', sa.Float(), nullable=False),
        sa.Column('medium', sa.Float(), nullable=False),
        sa.Column('high', sa.Float(), nullable=False),
        sa.Column('audit_level', sa.String(length=6), nullable=False),
        sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
        sa.PrimaryKeyConstraint('instrument_id'),
        info={"ifexists": True}
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument_thresholds', info={"ifexists": True})
    # ### end Alembic commands ###
